﻿﻿﻿﻿﻿﻿﻿const ERROR_CODES = {
  OK: 0,
  INVALID_PARAMS: 4000,
  UNSUPPORTED_MESSAGE_TYPE: 4001,
  FORBIDDEN: 4003,
  DOCUMENT_NOT_FOUND: 4004,
  CONFLICT: 4090,
  INTERNAL_ERROR: 5000,
};

const HTTP_STATUS_BY_ERROR_CODE = {
  [ERROR_CODES.OK]: 200,
  [ERROR_CODES.INVALID_PARAMS]: 400,
  [ERROR_CODES.UNSUPPORTED_MESSAGE_TYPE]: 400,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.DOCUMENT_NOT_FOUND]: 404,
  [ERROR_CODES.CONFLICT]: 409,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
};

function getHttpStatusByErrorCode(errorCode) {
  if (typeof errorCode !== 'number') {
    return HTTP_STATUS_BY_ERROR_CODE[ERROR_CODES.INTERNAL_ERROR];
  }

  return HTTP_STATUS_BY_ERROR_CODE[errorCode] || HTTP_STATUS_BY_ERROR_CODE[ERROR_CODES.INTERNAL_ERROR];
}

module.exports = {
  ERROR_CODES,
  HTTP_STATUS_BY_ERROR_CODE,
  getHttpStatusByErrorCode,
};
