﻿﻿const WS_MESSAGE_TYPES = {
  JOIN: 'join',
  JOIN_ACK: 'join_ack',
  PRESENCE: 'presence',
  SET_CELL: 'set_cell',
  CELL_UPDATED: 'cell_updated',
  INSERT_ROW: 'insert_row',
  ROW_INSERTED: 'row_inserted',
  DELETE_ROW: 'delete_row',
  ROW_DELETED: 'row_deleted',
  INSERT_COL: 'insert_col',
  COL_INSERTED: 'col_inserted',
  DELETE_COL: 'delete_col',
  COL_DELETED: 'col_deleted',
  SET_TITLE: 'set_title',
  TITLE_UPDATED: 'title_updated',
  ADD_SHEET: 'add_sheet',
  SHEET_ADDED: 'sheet_added',
  IMPORT_SHEET: 'import_sheet',
  SHEET_IMPORTED: 'sheet_imported',
  UNDO: 'undo',
  UNDO_APPLIED: 'undo_applied',
  REDO: 'redo',
  REDO_APPLIED: 'redo_applied',
  ERROR: 'error',
};

module.exports = {
  WS_MESSAGE_TYPES,
};
